name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '🐛 Fixes'
    labels: ['bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies']
  - title: '📝 Documentation'
    labels: ['documentation']
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No user-facing changes.'

# Body template for the release notes. $CHANGES will be replaced with the categorized list above.
template: |
  ## What’s Changed

  $CHANGES

  ## Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels: ['breaking-change']
  minor:
    labels: ['feature']
  patch:
    labels: ['bug', 'chore', 'documentation']
  default: patch
