name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution you’d like
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternatives you considered
