name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all --locked --verbose
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Tests
        run: cargo test --all --verbose
